<a href="https://colab.research.google.com/github/Debugger-Dev/Perceptron/blob/main/Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import os
import pandas as pd
import joblib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import ListedColormap


class Perceptron:
    def __init__(self,eta:int=None,epochs:int=None): #eta = learning rate,epoch=no of iteration 
        self.weights= np.random.randn(3) *1e-4  # 3 very small numbers (w0,w1,w2)
        training = (eta is not None) and (epochs is not  None)
        if training:
            print(f"Initial weights before training: \n{self.weights}")
        self.eta=eta
        self.epochs=epochs

    def _z_outcome(self, inputs, weights):
        return np.dot(inputs,weights)

    def activation_fun(self,z):    #unit step function
        return np.where(z>0,1,0)



    def fit(self,X,y):
        self.X=X
        self.y=y

        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")

        for epoch in range(self.epochs):
            print("-----"*10)
            print(f"for epoch >> {epoch}")
            print("-----"*10)

            z= self._z_outcome(X_with_bias,self.weights)
            y_hat = self.activation_fun(z)
            print(f"prediction after forward propagation is: \n{y_hat}")

            self.error= self.y - y_hat
            print(f"error: \n {self.error}")

            self.weights = self.weights + self.eta * np.dot(X_with_bias.T ,self.error)
            print(f"Updated weights after epoch: {epoch+1}/{self.epochs}: \n{self.weights}")
            print("******"*10)

    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z=self._z_outcome(X_with_bias,self.weights)
        return self.activation_fun(z)

    def total_loss(self):
        total_loss = np.sum(self.error)
        print(f"\ntotal loss:{total_loss}\n")
        return total_loss


    def _create_dir_return_path(self,model_dir,filename):
        os.makedirs(model_dir,exist_ok=True)
        return os.path.join(model_dir,filename)

    def save(self,filename,model_dir=None):
        if model_dir is not None:
            model_file_path = self._create_dir_return_path(model_dir,filename)
            joblib.dump(self,model_file_path)
        else:
            model_file_path = self._create_dir_return_path("model",filename)
            joblib.dump(self,model_file_path)


    def load(self,filepath):
        return joblib.load(filepath)



In [10]:
AND = {
    "x1":[0,1,0,1],
    "x2":[0,0,1,1],
    "y":[0,0,0,1]
}

df=pd.DataFrame(AND)
#print(df)

def prepare_data(df,target_col="y"):
    X=df.drop(target_col,axis=1)
    y=df[target_col]
    return X,y

In [11]:
X,y =prepare_data(df)
ETA = 0.1
EPOCHS = 10

model_and = Perceptron(eta=ETA,epochs=EPOCHS)
model_and.fit(X,y)

_ = model_and.total_loss()

Initial weights before training: 
[-0.00014385 -0.00017286 -0.00013914]
X with bias: 
[[ 0.  0. -1.]
 [ 1.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  1. -1.]]
--------------------------------------------------
for epoch >> 0
--------------------------------------------------
prediction after forward propagation is: 
[1 0 0 0]
error: 
 0   -1
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights after epoch: 1/10: 
[ 0.09985615  0.09982714 -0.00013914]
************************************************************
--------------------------------------------------
for epoch >> 1
--------------------------------------------------
prediction after forward propagation is: 
[1 1 1 1]
error: 
 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights after epoch: 2/10: 
[-1.43848361e-04 -1.72859970e-04  2.99860862e-01]
************************************************************
--------------------------------------------------
for epoch >> 2
-------------------------------------------------

In [12]:
OR = {
    "x1":[0,1,0,1],
    "x2":[0,0,1,1],
    "y":[0,1,1,1]
}

df=pd.DataFrame(OR)
#print(df)

def prepare_data(df,target_col="y"):
    X=df.drop(target_col,axis=1)
    y=df[target_col]
    return X,y



In [13]:
X,y =prepare_data(df)
ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA,epochs=EPOCHS)
model_or.fit(X,y)

_ = model_or.total_loss()

Initial weights before training: 
[8.03903334e-05 6.25174310e-05 5.04284378e-05]
X with bias: 
[[ 0.  0. -1.]
 [ 1.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  1. -1.]]
--------------------------------------------------
for epoch >> 0
--------------------------------------------------
prediction after forward propagation is: 
[0 1 1 1]
error: 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epoch: 1/10: 
[8.03903334e-05 6.25174310e-05 5.04284378e-05]
************************************************************
--------------------------------------------------
for epoch >> 1
--------------------------------------------------
prediction after forward propagation is: 
[0 1 1 1]
error: 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epoch: 2/10: 
[8.03903334e-05 6.25174310e-05 5.04284378e-05]
************************************************************
--------------------------------------------------
for epoch >> 2
----------------------------------

In [14]:
XOR = {
    "x1":[0,1,0,1],
    "x2":[0,0,1,1],
    "y":[0,1,1,0]
}

df=pd.DataFrame(XOR)
#print(df)

def prepare_data(df,target_col="y"):
    X=df.drop(target_col,axis=1)
    y=df[target_col]
    return X,y

In [15]:
X,y =prepare_data(df)
ETA = 0.1
EPOCHS = 10

model_xor = Perceptron(eta=ETA,epochs=EPOCHS)
model_xor.fit(X,y)

_ = model_xor.total_loss()

Initial weights before training: 
[ 1.86898985e-05  2.26439540e-04 -1.73283100e-04]
X with bias: 
[[ 0.  0. -1.]
 [ 1.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  1. -1.]]
--------------------------------------------------
for epoch >> 0
--------------------------------------------------
prediction after forward propagation is: 
[1 1 1 1]
error: 
 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights after epoch: 1/10: 
[-0.09998131 -0.09977356  0.19982672]
************************************************************
--------------------------------------------------
for epoch >> 1
--------------------------------------------------
prediction after forward propagation is: 
[0 0 0 0]
error: 
 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights after epoch: 2/10: 
[ 1.86898985e-05  2.26439540e-04 -1.73283100e-04]
************************************************************
--------------------------------------------------
for epoch >> 2
-------------------------------------

In [16]:
def save_plot(df,model):
  X,y = prepare_data(df)

  def _create_base_plot(df):
    df.plot(kind="scatter",x="x1",y="x2",c="y",s=100)
    plt.axhline(y=0,color="black",linestyle="--",linewidth=1)
    plt.axvline(x=0,color="black",linestyle="--",linewidth=1)

    figure=plt.gcf
    figure.set_size_inches(10,8)
  def _plot_decission_region(X,y,classifier):
    colors=("Cyan","lightgreen")
    cmap=ListedColormap(colors)

    

  _create_base_plot(df)
  _plot_decission_region(X,y,model)
